name = "UnivariateFunctions"
uuid = "368b7869-440d-5a68-a3d1-bbc86b0a93b0"
authors = ["Stuart Baumann <stuart@stuartbaumann.com>"]
version = "1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
NonNegLeastSquares = "b7351bd1-99d9-5c5d-8786-f205a815c4d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SchumakerSpline = "65e68595-3a03-5ff5-a6a2-f05fa774f32e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimeZones = "f269a46b-ccf7-5d73-abea-4c690281aa53"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
DataFrames = "^1.7.0"
Dates = "^1.11.0"
Distributions = "^0.25.120"
GLM = "^1.0"
MultivariateStats = "^0.10.3"
NonNegLeastSquares = "^0.4.1"
Random = "^1.11.0"
SchumakerSpline = "^1.4"
Statistics = "^1"
Test = "^1.11.0"
TimeZones = "^1.22.0"
UUIDs = "^1.11.0"
VegaLite = "^3.3.0"
julia = "^1.0"
